version: '3'

services:
  gpt4free:
    image: hlohaus789/g4f:latest
    shm_size: 2gb
    volumes:
      - ./hardir:/app/hardir
    ports:
      - '8080:8080'
      - '1337:1337'
      - '7900:7900'
